### ISSUE TITLE
set defaultChecked for checkbox

### ISSUE THREAD

**Issue by aaronsmulktis** [coniel/meteor-react-form-handler#15]
the checkbox component does not respect any of the following passed props:

check={}
defaultChecked={}
checked={}

Is there a way to set the status of the checkbox when setting initial state when component loads?

**Comment by aaronsmulktis** [comment]
otherwise totally loving this module!! thanks for all the great work

**Comment by coniel** [comment]
Hey, glad you like it!

You should be able to pass the initial state using defaultValue={} or by passing a doc to the form which has the initial value.

So basically defaultValue={true} for checked.

**Comment by aaronsmulktis** [comment]
that worked!! thanks..
