### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by davidschenz** [coniel/meteor-react-form-handler#3]
Thanks for writing this one. I'm using it on a new project and it seems to work pretty well. Anyways, one item that I had a form that was missing an input box for a required field in the schema. Debugging it was very frustrating b/c it wasn't writing out any input. SimpleSchemas has a debug mode that will give you some output on what is going wrong. 

If I get some time this week, I'll work on a pull request.

Thanks!

**Comment by coniel** [comment]
Hey, yeah, I've been planning on adding this but I'm a bit busy at the moment. A PR would be great, although the code isn't really commented yet so you might have a hard time figuring some stuff out (I'll comment everything this week). Let me know if/when you start and if you have any issues.

**Comment by coniel** [comment]
I've added a debug setting which for now just prints out validation errors to the console (which includes fields that are missing/failed validation and fields that are not supposed to be there (i.e. are not in the schema)). I'll improve it to be more helpful soon. Let me know if you want something else to be printed out as well.

To enable it, add `FormHandler.debug = true;` inside a `Meteor.startup` call.
