### ISSUE TITLE
Can it render form with some data?

### ISSUE THREAD

**Issue by chompomonim** [coniel/meteor-react-form-handler#6]
In docs there are only example how to render form, but there are no information about passing current data, for edit type of forms.

**Comment by coniel** [comment]
Sorry for the late reply. You can pass current data through the doc property, e.g:

```
<Form id="update-post-form" schema={PostSchema} onSubmit={this.updatePost} doc={post}>
...
</Form>
```

I added this recently, still need to update the docs.

**Comment by chompomonim** [comment]
Thanks
