### ISSUE TITLE
Radio button and checkbox not going through.

### ISSUE THREAD

**Issue by ncrmro** [coniel/meteor-react-form-handler#7]
I have a value that is yes or no, the boolean checkbox and radio buttons (with string values Yes or No) don't work.

But if I put a text input with a string it goes through fine.

**Comment by coniel** [comment]
Could you share the relevant part of the code? Also, which UI package are you using (Material UI or Semantic UI)?

**Comment by ncrmro** [comment]
Apologies it's all working, just made the switch to react and had to clean up some packages. Thank you the package is fantastic!

**Comment by coniel** [comment]
Good to know!
