### ISSUE TITLE
GNU License

### ISSUE THREAD

**Issue by tommiley** [coniel/meteor-react-form-handler#9]
I like what you have done with this library and would like to contribute to it (specifically, a bootstrap version). The GNU license prevents me from using this library on client projects. Can the license be changed to MIT?

**Comment by coniel** [comment]
Thanks, it would be great to have a bootstrap version! I've changed the license to MIT (not sure why I was using GNU in the first place).

**Comment by macrozone** [comment]
small notice: you credited Eric Dobbertin (aldeed) in the licence ;-)

**Comment by coniel** [comment]
Oh wow, good catch! I copied the license from the autoform repo, should have double checked... Will fix in the next release.
